
port: 8080

mysql: &mysql
  host: ip.xueboren.cn
  port: 3306
  username: uxadmin
  password: pXadmin_110
  database: xadmin

typeorm:
  options:
    type: mysql
    <<: *mysql
    host: host.docker.internal

express:
  authTokenCookie:
    httpOnly: false

logger:
  console: true
  aliyun: false
