
port: 8080

mysql: &mysql
  host: 172.16.3.118
  port: 3306
  username: uxadmin
  password: pXadmin_110
  database: xadmin

typeorm:
  options:
    type: mysql
    <<: *mysql

express:
  authTokenCookie:
    httpOnly: false

logger:
  console: true
  aliyun: false
